### PR TITLE
Add method: clear

### PR DESCRIPTION
**Pull request by Vacxe**
@Malinskiy Hi Anton. I think that method is very useful in SharedPreferences. I hope than my little improve will help your library. With best regards.

### CODE REVIEW

**Comment by Malinskiy** [comment]
@vacxe Hey! Thanks a lot for this PR!
The implementation seems fine. The only thing missing here are some tests. Could you please take a look at PreferencesProcessorTest as an example and implement at least 1 test case for testing clear?

Thanks!

**Comment by Vacxe** [comment]
@malinskiy Yep, i will create test tommorow. Righ now im not at home.

**Comment by Vacxe** [comment]
@Malinskiy Anton, i saw your test cases, and i have some questions.
 - This commit changes has not dependent with annotated interface
 - "clear" method will be add to all generated classes bcoz it base SharedPreferences.Editor function.

Therefore if your test cases based on mock interfaces new functional don't broke it, and will be add to all test (If you testing compile exception).

**Comment by Malinskiy** [comment]
@vacxe your test case should assert that your code generation (in this case the generateCode method in the Cleaner class) actually produces valid code. This is done by having a test interface implementation, running the annotation processor on it and then asserting this to predefined source code that you expect to be generated.

**Comment by Vacxe** [comment]
@Malinskiy ok, i will try. Its new experience for me.

**Comment by Vacxe** [comment]
@Malinskiy all right?

**Pull request merged**
